name: CI for Ibis

on: [push, pull_request]

jobs:

  check-ibis:
    runs-on: ${{ matrix.operating-system}}
    strategy:
      matrix:
        operating-system: ['ubuntu-latest', 'windows-latest', 'macos-14']
        php-versions: [ '8.3' ]
    name: P${{ matrix.php-versions }} - ${{ matrix.operating-system}}
    steps:
      # This is required as this package does not support PHP 8 (yet)
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: gd

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Composer Install
        run: "composer update"

      - name: test Ibis Next execution
        run: |
          mkdir export
          ./ibis-next init
          ./ibis-next pdf
          ./ibis-next epub
          ./ibis-next html
