name: CI for Ibis

on: [push, pull_request]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-system: ['ubuntu-latest']
        php-versions: [ '8.3' ]
    name: P${{ matrix.php-versions }} - L${{ matrix.laravel }} - ${{ matrix.dependency-stability }} - ${{ matrix.operating-system}}
    steps:
      # This is required as this package does not support PHP 8 (yet)
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Use Composer Cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Composer Install
        run: "composer install --no-ansi --no-interaction --no-scripts --prefer-dist"

      - name: Execute PHP CS Fixer review
        run: composer run csfix-review

  check-ibis:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-system: ['ubuntu-latest', 'windows-latest']
        php-versions: [ '8.3', '8.2','8.1' ]
    name: P${{ matrix.php-versions }} - L${{ matrix.laravel }} - ${{ matrix.dependency-stability }} - ${{ matrix.operating-system}}
    steps:
      # This is required as this package does not support PHP 8 (yet)
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Use Composer Cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Composer Install
        run: "composer update"

      - name: test Ibis execution
        run: |
          mkdir export
          ./ibis-next init
          ./ibis-next build
